const data: Object[] = [
  {
    title: "Tshirt with tape details",
    brand: "Zara",
    description:
      "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
    price: 450,
    image: "/img/Arrivals/image7.png",
    rating: 3,
    colors: ["red", "blue", "green", "pink", "yellow"],
    sizes: ["S", "M", "L", "X", "XL", "XXL"],
  },
  {
    title: "Skinny Fit Jeans",
    brand: "Zara",
    description:
      "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
    price: 390,
    image: "/img/Arrivals/image8.png",
    rating: 4,
    colors: ["red", "blue", "green", "yellow"],
    sizes: ["S", "M", "L", "X", "XL", "XXL"],
  },
  {
    title: "Checkered Shirt",
    brand: "Zara",
    description:
      "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
    price: 599,
    image: "/img/Arrivals/image9.png",
    rating: 3,
    colors: ["orange", "olive", "green", "yellow"],
    sizes: ["S", "M", "L", "X", "XL", "XXL"],
  },
  {
    title: "Men Regular Fit Short-Sleeved Lyocell Shirt",
    brand: "Kelvin Klein",
    description:
      "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
    price: 699,
    image: "/img/Arrivals/image11.png",
    rating: 5,
    discount: 4,
    colors: ["orange", "olive", "green", "yellow", "violet"],
    sizes: ["S", "M", "L", "X", "XL", "XXL"],
  },
  {
    title: "Vertical striped  shirt",
    brand: "Being Human",
    description:
      "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
    price: 820,
    image: "/img/Best_Selling/image7.png",
    rating: 5,
    discount: 8,
    colors: [
      "orange",
      "olive",
      "green",
      "yellow",
      "violet",
      "grey",
      "darkblue",
    ],
    sizes: ["xs", "S", "M", "L", "X", "XL", "XXL"],
  },
  {
    title: "Courage Graphic T-shirt",
    brand: "Versace",
    description:
      "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
    price: 220,
    image: "/img/Best_Selling/image8.png",
    rating: 3,
    colors: [
      "orange",
      "olive",
      "green",
      "yellow",
      "violet",
      "grey",
      "darkblue",
    ],
    sizes: ["xs", "S", "M", "L", "X", "XL", "XXL"],
  },
  {
    title: "Loose Fit Bermuda Shorts",
    brand: "Prada",
    description:
      "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
    price: 449,
    image: "/img/Best_Selling/image9.png",
    rating: 4,
    discount: 10,
    colors: [
      "orange",
      "olive",
      "green",
      "yellow",
      "violet",
      "grey",
      "darkblue",
    ],
    sizes: ["xs", "S", "M", "L", "X", "XL", "XXL"],
  },
  {
    title: "Sleeve Striped T-shirt",
    brand: "Gucci",
    description:
      "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
    price: 399,
    image: "/img/Arrivals/image10.png",
    rating: 4,
    colors: [
      "orange",
      "olive",
      "green",
      "yellow",
      "violet",
      "grey",
      "darkblue",
    ],
    sizes: ["xs", "S", "M", "L", "X", "XL", "XXL"],
  },
  {
    title: "Polo with Contrast Trims",
    brand: "Zara",
    description:
      "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
    price: 242,
    image: "/img/tshirts/image7.png",
    rating: 4,
    discount: 20,
    colors: [
      "orange",
      "olive",
      "green",
      "yellow",
      "violet",
      "grey",
      "darkblue",
    ],
    sizes: ["xs", "S", "M", "L", "X", "XL", "XXL"],
  },
  {
    title: "Gradient Graphic T-Shirt",
    brand: "H&Q",
    description:
      "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
    price: 145,
    image: "/img/tshirts/image8.png",
    rating: 4,
    colors: [
      "orange",
      "olive",
      "green",
      "yellow",
      "violet",
      "grey",
      "darkblue",
    ],
    sizes: ["xs", "S", "M", "L", "X", "XL", "XXL"],
  },
  {
    title: "Polo with Tipping Details",
    brand: "Kalwin Klein",
    description:
      "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
    price: 180,
    image: "/img/tshirts/image9.png",
    rating: 2,
    colors: [
      "orange",
      "olive",
      "green",
      "yellow",
      "violet",
      "grey",
      "darkblue",
    ],
    sizes: ["xs", "S", "M", "L", "X", "XL", "XXL"],
  },
  {
    title: "Black striped T-Shirt",
    brand: "Adidas",
    description:
      "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
    price: 280,
    image: "/img/tshirts/image10.png",
    rating: 3,
    colors: [
      "orange",
      "olive",
      "green",
      "yellow",
      "violet",
      "grey",
      "darkblue",
    ],
    sizes: ["xs", "S", "M", "L", "X", "XL", "XXL"],
  },
];
